from __future__ import annotations

import copy
import json
import struct
import zlib
from pathlib import Path
from typing import Any

from core.exceptions import ComfyUIError


_PNG_SIGNATURE = b'\x89PNG\r\n\x1a\n'


def extract_workflow_from_png(path: str) -> dict:
    """Extract a ComfyUI API-format workflow dict from a PNG file.

    Reads ``tEXt`` and ``iTXt`` metadata chunks, trying the ``"workflow"``
    key first (written by ComfyWeave / ComfyUI API output) then ``"prompt"``
    (written by ComfyUI's standard UI save).  Raises ``ValueError`` if no
    usable workflow is found.
    """
    file_path = Path(path)
    if not file_path.exists():
        raise FileNotFoundError(f"File not found: {path}")

    with file_path.open("rb") as fh:
        sig = fh.read(8)
        if sig != _PNG_SIGNATURE:
            raise ValueError("Not a valid PNG file.")

        text_chunks: dict[str, str] = {}
        while True:
            hdr = fh.read(8)  # 4-byte length + 4-byte type
            if len(hdr) < 8:
                break
            length = struct.unpack(">I", hdr[:4])[0]
            chunk_type = hdr[4:].decode("ascii", errors="replace")
            data = fh.read(length)
            fh.read(4)  # CRC (skip)

            if chunk_type == "tEXt":
                try:
                    null = data.index(b"\x00")
                    keyword = data[:null].decode("latin-1")
                    text = data[null + 1:].decode("latin-1")
                    text_chunks[keyword] = text
                except (ValueError, UnicodeDecodeError):
                    pass

            elif chunk_type == "iTXt":
                try:
                    null = data.index(b"\x00")
                    keyword = data[:null].decode("latin-1")
                    rest = data[null + 1:]
                    comp_flag = rest[0]
                    rest = rest[2:]  # skip comp_flag + comp_method
                    rest = rest[rest.index(b"\x00") + 1:]  # skip language tag
                    rest = rest[rest.index(b"\x00") + 1:]  # skip translated keyword
                    text_bytes = zlib.decompress(rest) if comp_flag else rest
                    text_chunks[keyword] = text_bytes.decode("utf-8")
                except (ValueError, zlib.error, UnicodeDecodeError):
                    pass

            if chunk_type == "IEND":
                break

    for key in ("workflow", "prompt"):
        raw_text = text_chunks.get(key)
        if raw_text is None:
            continue
        try:
            return json.loads(raw_text)
        except json.JSONDecodeError:
            continue

    raise ValueError(
        "No ComfyUI workflow metadata found in this PNG.\n\n"
        "The image must have been generated by ComfyUI with 'Save Image' "
        "or by ComfyWeave."
    )


def _extract_workflow_from_png_bytes(raw: bytes) -> dict:
    """Like ``extract_workflow_from_png`` but operates on in-memory bytes."""
    import io as _io
    fh = _io.BytesIO(raw)
    sig = fh.read(8)
    if sig != _PNG_SIGNATURE:
        raise ValueError("Not a valid PNG file.")

    text_chunks: dict[str, str] = {}
    while True:
        hdr = fh.read(8)
        if len(hdr) < 8:
            break
        length = struct.unpack(">I", hdr[:4])[0]
        chunk_type = hdr[4:].decode("ascii", errors="replace")
        data = fh.read(length)
        fh.read(4)  # CRC

        if chunk_type == "tEXt":
            try:
                null = data.index(b"\x00")
                keyword = data[:null].decode("latin-1")
                text = data[null + 1:].decode("latin-1")
                text_chunks[keyword] = text
            except (ValueError, UnicodeDecodeError):
                pass

        elif chunk_type == "iTXt":
            try:
                null = data.index(b"\x00")
                keyword = data[:null].decode("latin-1")
                rest = data[null + 1:]
                comp_flag = rest[0]
                rest = rest[2:]
                rest = rest[rest.index(b"\x00") + 1:]
                rest = rest[rest.index(b"\x00") + 1:]
                text_bytes = zlib.decompress(rest) if comp_flag else rest
                text_chunks[keyword] = text_bytes.decode("utf-8")
            except (ValueError, zlib.error, UnicodeDecodeError):
                pass

        if chunk_type == "IEND":
            break

    for key in ("workflow", "prompt"):
        raw_text = text_chunks.get(key)
        if raw_text is None:
            continue
        try:
            return json.loads(raw_text)
        except json.JSONDecodeError:
            continue

    raise ValueError(
        "No ComfyUI workflow metadata found in this PNG.\n\n"
        "The image must have been generated by ComfyUI with 'Save Image' "
        "or by ComfyWeave."
    )


# Node classes we surface as editable in the workflow panel.
# Add entries here whenever a new node type should be user-editable.
_EDITABLE_NODE_CLASSES = {
    # Samplers
    "KSampler",
    "KSamplerAdvanced",
    # Text conditioning
    "CLIPTextEncode",
    "CLIPTextEncodeSDXL",
    "CLIPTextEncodeSDXLRefiner",
    # Model / checkpoint loaders
    "CheckpointLoaderSimple",
    "CheckpointLoader",
    "UNETLoader",
    "DualCLIPLoader",
    "CLIPLoader",
    # LoRA / adapters
    "LoraLoader",
    "LoraLoaderModelOnly",
    # VAE
    "VAELoader",
    "VAEDecode",
    "VAEEncode",
    # Latent image (resolution) nodes — this is the most common place for width/height
    "EmptyLatentImage",
    "EmptySD3LatentImage",
    "EmptyFlux2LatentImage",
    "EmptyHunyuanLatentVideo",
    "EmptyMochiLatentVideo",
    "EmptyLTXVLatentVideo",
    "EmptyCogVideoXLatentVideo",
    "EmptyCogVideoXVideo",
    "LatentUpscale",
    "LatentUpscaleBy",
    # Flux2 / advanced sampler nodes
    "Flux2Scheduler",
    "KSamplerSelect",
    "CFGGuider",
    "RandomNoise",
    "SamplerCustomAdvanced",
    # Primitive value nodes (PrimitiveInt titles like "Width", "Height" drive the label)
    "PrimitiveInt",
    "PrimitiveStringMultiline",
    # Output
    "SaveImage",
    "PreviewImage",
    # Upscaling
    "UpscaleModelLoader",
    "ImageUpscaleWithModel",
}

# Input names that should be treated as "primary" / shown prominently
_PRIMARY_INPUTS = {"text", "ckpt_name", "seed", "steps", "cfg", "sampler_name",
                   "scheduler", "denoise", "width", "height", "batch_size"}


class EditableNode:
    """Represents one workflow node whose inputs can be overridden via the UI."""

    def __init__(self, node_id: str, class_type: str, inputs: dict) -> None:
        self.node_id = node_id
        self.class_type = class_type
        self.inputs = inputs  # original input values
        self.title: str = ""  # from _meta.title if present
        # Set when this is a PrimitiveInt "width" node paired with a separate "height" node
        self.paired_height_node_id: str | None = None
        self.paired_height_value: int | None = None
        # Set on the "height" PrimitiveInt so it is excluded from the returned list
        self.skip: bool = False

    def __repr__(self) -> str:
        return f"EditableNode({self.node_id}, {self.class_type})"


class WorkflowManager:
    """Loads, validates, and prepares ComfyUI workflow JSON for submission."""

    def __init__(self) -> None:
        self._raw: dict = {}
        self._path: str = ""

    # ------------------------------------------------------------------
    # Loading
    # ------------------------------------------------------------------

    def load_from_file(self, path: str) -> None:
        """Parse and validate a workflow JSON file exported from ComfyUI."""
        file_path = Path(path)
        if not file_path.exists():
            raise FileNotFoundError(f"Workflow file not found: {path}")
        if file_path.suffix.lower() != ".json":
            raise ValueError("Workflow file must be a .json file")

        with file_path.open("r", encoding="utf-8") as fh:
            data = json.load(fh)

        self._validate(data)
        self._raw = data
        self._path = path

    def load_from_png(self, path: str) -> None:
        """Extract and load an API-format workflow embedded in a PNG file."""
        data = extract_workflow_from_png(path)
        self._validate(data)
        self._raw = data
        self._path = path

    def load_from_png_bytes(self, raw: bytes) -> None:
        """Extract and load a workflow from in-memory PNG bytes (e.g. fetched from server)."""
        data = _extract_workflow_from_png_bytes(raw)
        self._validate(data)
        self._raw = data
        self._path = ""

    def load_from_dict(self, data: dict) -> None:
        """Load workflow from an already-parsed dict (e.g. from history)."""
        self._validate(data)
        self._raw = data
        self._path = ""

    @property
    def is_loaded(self) -> bool:
        return bool(self._raw)

    @property
    def path(self) -> str:
        return self._path

    # ------------------------------------------------------------------
    # Introspection
    # ------------------------------------------------------------------

    def get_editable_nodes(self) -> list[EditableNode]:
        """Return nodes whose class_type is in the editable set."""
        nodes: list[EditableNode] = []
        for node_id, node_data in self._raw.items():
            class_type = node_data.get("class_type", "")
            if class_type not in _EDITABLE_NODE_CLASSES:
                continue
            inputs = node_data.get("inputs", {})
            # Filter out link references (lists) — only keep literal values
            literal_inputs = {
                k: v for k, v in inputs.items()
                if not isinstance(v, list)
            }
            node = EditableNode(node_id, class_type, literal_inputs)
            node.title = node_data.get("_meta", {}).get("title", class_type)
            nodes.append(node)
        # Sort: primary-interest nodes first, then alphabetically by class
        nodes.sort(key=lambda n: (n.class_type not in {"KSampler", "CLIPTextEncode"}, n.class_type))
        # Detect paired PrimitiveInt nodes (separate width/height primitive nodes)
        self._detect_prim_int_pairs(nodes)
        # Exclude height nodes that are now represented inside the paired width node
        return [n for n in nodes if not n.skip]

    def _detect_prim_int_pairs(self, nodes: list[EditableNode]) -> None:
        """Scan the raw workflow for width/height ref-pairs that point to PrimitiveInt nodes.

        When found, the "width" node is annotated with the height node's id/value and
        the "height" node is marked ``skip=True`` so it doesn't get its own form.
        """
        # Build the set of PrimitiveInt node IDs that have a literal int 'value'
        prim_int_ids: set[str] = {
            n.node_id for n in nodes
            if n.class_type == "PrimitiveInt" and isinstance(n.inputs.get("value"), int)
        }
        if not prim_int_ids:
            return

        # Scan ALL raw nodes for inputs that reference two different PrimitiveInt nodes
        # via 'width' and 'height' link slots.
        width_height_pairs: set[tuple[str, str]] = set()  # (width_prim_id, height_prim_id)
        for node_data in self._raw.values():
            raw_inputs = node_data.get("inputs", {})
            w_ref = raw_inputs.get("width")
            h_ref = raw_inputs.get("height")
            if (
                isinstance(w_ref, list) and len(w_ref) >= 1
                and isinstance(h_ref, list) and len(h_ref) >= 1
            ):
                w_id = str(w_ref[0])
                h_id = str(h_ref[0])
                if w_id in prim_int_ids and h_id in prim_int_ids and w_id != h_id:
                    width_height_pairs.add((w_id, h_id))

        if not width_height_pairs:
            return

        prim_node_map: dict[str, EditableNode] = {
            n.node_id: n for n in nodes if n.class_type == "PrimitiveInt"
        }

        claimed_height_ids: set[str] = set()
        for w_id, h_id in width_height_pairs:
            if h_id in claimed_height_ids:
                continue  # already paired with another width node
            w_node = prim_node_map.get(w_id)
            h_node = prim_node_map.get(h_id)
            if w_node and h_node and w_node.paired_height_node_id is None:
                w_node.paired_height_node_id = h_id
                w_node.paired_height_value = h_node.inputs.get("value", w_node.inputs.get("value"))
                w_node.title = "Width / Height"
                h_node.skip = True
                claimed_height_ids.add(h_id)

    def get_all_node_ids(self) -> list[str]:
        return list(self._raw.keys())

    # ------------------------------------------------------------------
    # Building the payload
    # ------------------------------------------------------------------

    def apply_overrides(self, overrides: dict[str, dict[str, Any]]) -> dict:
        """Return a copy of the workflow with node input overrides applied.

        ``overrides`` format: { "<node_id>": { "<input_name>": <value>, ... }, ... }
        """
        workflow = copy.deepcopy(self._raw)
        for node_id, input_patch in overrides.items():
            if node_id in workflow:
                workflow[node_id]["inputs"].update(input_patch)
        return workflow

    def to_prompt_payload(self, client_id: str, overrides: dict | None = None) -> dict:
        """Build the full ``POST /prompt`` body dict."""
        workflow = self.apply_overrides(overrides or {})
        return {
            "prompt": workflow,
            "client_id": client_id,
            "extra_data": {"extra_pnginfo": {"workflow": workflow}},
        }

    def raw_copy(self) -> dict:
        return copy.deepcopy(self._raw)

    # ------------------------------------------------------------------
    # Validation
    # ------------------------------------------------------------------

    @staticmethod
    def _validate(data: Any) -> None:
        if not isinstance(data, dict):
            raise ComfyUIError("Workflow JSON must be a top-level object (dict).")
        if not data:
            raise ComfyUIError("Workflow JSON is empty.")

        # Detect the regular UI workflow format (has "nodes", "links", "version" keys)
        ui_format_keys = {"nodes", "links", "version", "last_node_id", "last_link_id"}
        if ui_format_keys.intersection(data.keys()):
            raise ComfyUIError(
                "This looks like a standard ComfyUI workflow file, not an API-format file.\n\n"
                "To get the correct format:\n"
                "  1. Open ComfyUI in your browser\n"
                "  2. Go to Settings → Enable Dev Mode Options\n"
                "  3. In the workflow menu (top-right), choose \"Save (API Format)\"\n\n"
                "The API format file has node IDs as top-level keys (e.g. \"1\", \"2\", …)."
            )

        # Each value should be a node dict with class_type
        for key, val in data.items():
            if not isinstance(val, dict):
                raise ComfyUIError(
                    f"Workflow node '{key}' has an unexpected value (expected a dict, got {type(val).__name__}).\n\n"
                    "Make sure you export the workflow using \"Save (API Format)\" from ComfyUI."
                )
